create table if not exists public.learner_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.learner_state enable row level security;

create policy "read own learner state" on public.learner_state
for select using (auth.uid() = user_id);

create policy "insert own learner state" on public.learner_state
for insert with check (auth.uid() = user_id);

create policy "update own learner state" on public.learner_state
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.study_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.study_events enable row level security;

create policy "read own study events" on public.study_events
for select using (auth.uid() = user_id);

create policy "insert own study events" on public.study_events
for insert with check (auth.uid() = user_id);

create index if not exists study_events_user_created_idx
on public.study_events(user_id, created_at desc);
